name: Unit Tests

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - '.github/workflows/deploy.yml'
      - '.github/workflows/deployStaging.yml'
      - '.editorconfig'
      - '.styleci.yml'

jobs:
  unit-tests:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Copy .env
      run: cp .env.example .env

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npx hardhat test
